/**
 * Write-only master-key / .env.wallet helpers (agent-safe).
 *
 * Never print the key. Never overwrite an existing .env.wallet.
 * Pure-ish functions for tests + install-for-host / generate-wallet-env CLIs.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  chmodSync,
  constants as fsConstants,
} from "node:fs";
import { resolve, dirname, join } from "node:path";
import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";

/** 64-char hex master key (32 bytes). */
export function generateMasterKeyHex() {
  return randomBytes(32).toString("hex");
}

/** True when text looks like a 64-char hex master key (case-insensitive). */
export function looksLikeMasterKeyHex(text) {
  if (typeof text !== "string") return false;
  return /\b[0-9a-fA-F]{64}\b/.test(text);
}

/**
 * Best-effort restrictive file mode (Unix 0o600). On Windows, chmod is limited;
 * callers should document that ACLs are operator-managed.
 * @returns {{ ok: boolean, mode?: number, note?: string }}
 */
export function tryRestrictiveFileMode(filePath, mode = 0o600) {
  try {
    chmodSync(filePath, mode);
    return { ok: true, mode };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return {
      ok: false,
      note: `Could not set mode ${mode.toString(8)} on ${filePath}: ${msg}. On Windows, use NTFS ACLs or keep the file out of shared folders.`,
    };
  }
}

/**
 * Best-effort restrictive directory mode (Unix 0o700).
 * @returns {{ ok: boolean, mode?: number, note?: string }}
 */
export function tryRestrictiveDirMode(dirPath, mode = 0o700) {
  try {
    if (!existsSync(dirPath)) {
      mkdirSync(dirPath, { recursive: true, mode });
    } else {
      chmodSync(dirPath, mode);
    }
    return { ok: true, mode };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // Still try to create without mode if mode failed mid-way
    try {
      if (!existsSync(dirPath)) mkdirSync(dirPath, { recursive: true });
    } catch {
      /* ignore */
    }
    return {
      ok: false,
      note: `Could not fully set dir mode ${mode.toString(8)} on ${dirPath}: ${msg}. On Windows, restrictive POSIX modes are not fully honored.`,
    };
  }
}

/**
 * Build .env.wallet body: prefer template from example when present, inject key.
 * @param {{ masterKey: string, exampleBody?: string | null, walletDir?: string }} opts
 */
export function buildWalletEnvBody(opts) {
  const masterKey = opts.masterKey;
  const walletDir = opts.walletDir ?? "./data/wallets";
  const example = opts.exampleBody;

  if (example && typeof example === "string" && example.trim()) {
    let body = example;
    // Fill empty AGENT_WALLET_MASTER_KEY= or AGENT_WALLET_MASTER_KEY=
    if (/^AGENT_WALLET_MASTER_KEY=\s*$/m.test(body)) {
      body = body.replace(
        /^AGENT_WALLET_MASTER_KEY=\s*$/m,
        `AGENT_WALLET_MASTER_KEY=${masterKey}`,
      );
    } else if (/^AGENT_WALLET_MASTER_KEY=.*$/m.test(body)) {
      body = body.replace(
        /^AGENT_WALLET_MASTER_KEY=.*$/m,
        `AGENT_WALLET_MASTER_KEY=${masterKey}`,
      );
    } else {
      body = body.trimEnd() + `\nAGENT_WALLET_MASTER_KEY=${masterKey}\n`;
    }
    if (!/^AGENT_WALLET_ENABLED=/m.test(body)) {
      body = `AGENT_WALLET_ENABLED=true\n` + body;
    }
    if (!/^AGENT_WALLET_DIR=/m.test(body)) {
      body = body.trimEnd() + `\nAGENT_WALLET_DIR=${walletDir}\n`;
    }
    return body.endsWith("\n") ? body : body + "\n";
  }

  return [
    "# Generated by pulsechain-mcp write-only key path — DO NOT COMMIT",
    "# Secrets live only in this gitignored file. Host config must not embed the key.",
    "AGENT_WALLET_ENABLED=true",
    `AGENT_WALLET_MASTER_KEY=${masterKey}`,
    `AGENT_WALLET_DIR=${walletDir}`,
    "AGENT_WALLET_MULTIPROC_STRICT=true",
    "LOG_LEVEL=info",
    "",
  ].join("\n");
}

/**
 * Create .env.wallet with a fresh key. Refuses if the file already exists.
 *
 * @param {{
 *   cloneRoot: string,
 *   envFileName?: string,
 *   exampleFileName?: string,
 *   walletDirRel?: string,
 *   masterKey?: string,
 * }} opts
 * @returns {{
 *   ok: boolean,
 *   created?: boolean,
 *   envPath?: string,
 *   walletDir?: string,
 *   fileMode?: { ok: boolean, mode?: number, note?: string },
 *   dirMode?: { ok: boolean, mode?: number, note?: string },
 *   error?: string,
 *   code?: string,
 *   messages: string[],
 * }}
 *
 * Success messages never include the key. On refuse-exists, no overwrite.
 */
export function createWalletEnvWriteOnly(opts) {
  const messages = [];
  const cloneRoot = resolve(opts.cloneRoot);
  const envName = opts.envFileName ?? ".env.wallet";
  const exampleName = opts.exampleFileName ?? ".env.wallet.example";
  const envPath = resolve(cloneRoot, envName);
  const examplePath = resolve(cloneRoot, exampleName);
  const walletDirRel = opts.walletDirRel ?? "./data/wallets";
  const walletDirAbs = resolve(cloneRoot, walletDirRel.replace(/^\.\//, ""));

  if (existsSync(envPath)) {
    messages.push(
      `${envName} already exists — refusing to overwrite (key safety).`,
    );
    messages.push(
      `If you need a new key, move or delete ${envPath} yourself, then re-run.`,
    );
    return {
      ok: false,
      created: false,
      envPath,
      code: "ENV_EXISTS",
      error: "refuse-overwrite",
      messages,
    };
  }

  const masterKey = opts.masterKey ?? generateMasterKeyHex();
  if (!/^[0-9a-fA-F]{64}$/.test(masterKey)) {
    return {
      ok: false,
      code: "INVALID_KEY",
      error: "master key must be 64 hex chars when provided",
      messages: ["Invalid master key shape (expected 64 hex characters)."],
    };
  }

  let exampleBody = null;
  if (existsSync(examplePath)) {
    exampleBody = readFileSync(examplePath, "utf8");
  }

  const body = buildWalletEnvBody({
    masterKey,
    exampleBody,
    walletDir: walletDirRel,
  });

  // Ensure parent exists
  mkdirSync(dirname(envPath), { recursive: true });
  writeFileSync(envPath, body, { encoding: "utf8", flag: "wx" });

  const fileMode = tryRestrictiveFileMode(envPath, 0o600);
  const dirMode = tryRestrictiveDirMode(walletDirAbs, 0o700);

  messages.push(`Created ${envName} (master key written to file only — not printed).`);
  messages.push(`Wallet data dir ensured: ${walletDirAbs}`);
  if (fileMode.ok) {
    messages.push(`File mode set to 600 where supported.`);
  } else if (fileMode.note) {
    messages.push(fileMode.note);
  }
  if (dirMode.ok) {
    messages.push(`Dir mode set to 700 where supported.`);
  } else if (dirMode.note) {
    messages.push(dirMode.note);
  }
  messages.push(
    "Verify secrets with existence checks / agent_wallet_status flags only — never read_file the key.",
  );

  // Defense: ensure we never accidentally put key into messages
  for (const m of messages) {
    if (m.includes(masterKey)) {
      throw new Error("internal: success messages must not contain master key");
    }
  }

  return {
    ok: true,
    created: true,
    envPath,
    walletDir: walletDirAbs,
    fileMode,
    dirMode,
    messages,
  };
}

/** Package root when this file lives at scripts/lib/wallet-env.mjs */
export function defaultPackageRoot() {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
}

export { existsSync, resolve, join, fsConstants };
